name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: ib-gateway
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
